# Generated by Django 6.0 on 2025-12-08 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_id', models.CharField(max_length=64, unique=True)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('resume_raw', models.TextField(blank=True, null=True)),
                ('present_location', models.CharField(blank=True, max_length=255, null=True)),
                ('permanent_location', models.CharField(blank=True, max_length=255, null=True)),
                ('total_experience_years', models.FloatField(blank=True, null=True)),
                ('current_designation', models.CharField(blank=True, max_length=255, null=True)),
                ('current_company', models.CharField(blank=True, max_length=255, null=True)),
                ('notice_period_days', models.IntegerField(blank=True, null=True)),
                ('salary_current', models.IntegerField(blank=True, null=True)),
                ('salary_expected', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=64, null=True)),
                ('domain', models.CharField(blank=True, max_length=64, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=32, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('center_vector', models.JSONField()),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=64, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('role_code', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('location_type', models.CharField(choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'OnSite')], default='onsite', max_length=32)),
                ('experience_min_years', models.FloatField(blank=True, null=True)),
                ('experience_max_years', models.FloatField(blank=True, null=True)),
                ('budget_min', models.IntegerField(blank=True, null=True)),
                ('budget_max', models.IntegerField(blank=True, null=True)),
                ('industry', models.CharField(blank=True, max_length=64, null=True)),
                ('domain', models.CharField(blank=True, max_length=64, null=True)),
                ('seniority_level', models.CharField(blank=True, max_length=32, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('on_hold', 'On hold'), ('closed', 'Closed')], default='open', max_length=32)),
                ('priority', models.CharField(default='medium', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('center_vector', models.JSONField()),
                ('size', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CandidateClusterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_to_center', models.FloatField()),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_membership', to='sourcing.candidate')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sourcing.candidatecluster')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('semantic_vector', models.JSONField(blank=True, null=True)),
                ('structured_vector', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='sourcing.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('issuing_org', models.CharField(blank=True, max_length=255, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('credential_id', models.CharField(blank=True, max_length=255, null=True)),
                ('credential_url', models.URLField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='sourcing.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('designation', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('responsibilities', models.TextField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='sourcing.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='JobClusterMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_to_center', models.FloatField()),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='sourcing.jobcluster')),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_membership', to='sourcing.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobVector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', models.JSONField()),
                ('semantic_vector', models.JSONField(blank=True, null=True)),
                ('structured_vector', models.JSONField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vector', to='sourcing.job')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateJobApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('interested', 'Interested'), ('recommended', 'Recommended'), ('submitted', 'Submitted'), ('placed', 'Placed'), ('rejected', 'Rejected'), ('not_interested', 'Not Interested')], default='interested', max_length=32)),
                ('source', models.CharField(blank=True, max_length=128, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('last_contacted_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_change_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='sourcing.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='sourcing.job')),
            ],
            options={
                'unique_together': {('candidate', 'job')},
            },
        ),
        migrations.CreateModel(
            name='JobCandidateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField()),
                ('skill_match_score', models.FloatField(blank=True, null=True)),
                ('semantic_match_score', models.FloatField(blank=True, null=True)),
                ('experience_match_score', models.FloatField(blank=True, null=True)),
                ('location_match_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sourcing.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='sourcing.job')),
            ],
            options={
                'indexes': [models.Index(fields=['job', '-score'], name='sourcing_jo_job_id_f875d0_idx')],
                'unique_together': {('job', 'candidate')},
            },
        ),
        migrations.CreateModel(
            name='ClusterCorrelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correlation', models.FloatField()),
                ('candidate_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_correlations', to='sourcing.candidatecluster')),
                ('job_cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_correlations', to='sourcing.jobcluster')),
            ],
            options={
                'indexes': [models.Index(fields=['job_cluster', '-correlation'], name='sourcing_cl_job_clu_526d74_idx')],
                'unique_together': {('job_cluster', 'candidate_cluster')},
            },
        ),
        migrations.CreateModel(
            name='JobSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importance', models.CharField(choices=[('must', 'Must have'), ('nice', 'Nice to have')], default='must', max_length=16)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_skills', to='sourcing.job')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcing.skill')),
            ],
            options={
                'unique_together': {('job', 'skill')},
            },
        ),
        migrations.CreateModel(
            name='CandidateSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proficiency', models.CharField(blank=True, choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=32, null=True)),
                ('years_of_experience', models.FloatField(blank=True, null=True)),
                ('last_used_year', models.IntegerField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_skills', to='sourcing.candidate')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sourcing.skill')),
            ],
            options={
                'unique_together': {('candidate', 'skill')},
            },
        ),
    ]
